/**
 * Iskay (FinOps chat) — Excel report store.
 *
 * Persists workbooks generated by the `build_report` tool in the `finops_reports`
 * table so the download endpoint (`GET /api/finops/report/[id]`) works across both
 * portal replicas regardless of which pod served the chat turn (cross-replica
 * persistence is the whole reason this lives in Postgres rather than in-memory).
 *
 * API:
 *  - saveReport({ filename, content, userEmail, ttlMinutes })
 *      Generates a UUID app-side (the migration intentionally has no pgcrypto
 *      dependency), inserts the buffer with the computed `expires_at`, and
 *      returns the `reportId`.
 *  - getReport(id)
 *      Returns `{ filename, content, userEmail }` only if the row exists AND has
 *      not expired. Expired rows are treated as inexistent and lazily deleted
 *      (best-effort), so a follow-up read returns null without scheduling extra
 *      cleanup work.
 *
 * Notes:
 *  - `id` is validated as a UUID before hitting the DB so a malformed download
 *    URL returns null cleanly instead of bubbling up a Postgres syntax error.
 *  - Ownership (user_email vs session) is checked by the download endpoint, not
 *    here; this module is the pure persistence layer.
 *  - TTL is short by design (minutes); cleanup of stale rows can ride on the
 *    `idx_finops_reports_expires_at` index when/if a sweeper job is added.
 */

import { randomUUID } from "node:crypto";

import pool from "@/lib/db";

const UUID_REGEX =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

export interface SaveReportInput {
  filename: string;
  content: Buffer;
  userEmail: string;
  /** Time-to-live in minutes. Must be a positive finite number. */
  ttlMinutes: number;
}

export interface StoredReport {
  filename: string;
  content: Buffer;
  userEmail: string;
}

/**
 * Persists a workbook buffer and returns the freshly-generated `reportId`.
 *
 * The UUID is generated app-side (Node `crypto.randomUUID`) to keep the migration
 * free of `pgcrypto` / `uuid-ossp` dependencies.
 */
export async function saveReport({
  filename,
  content,
  userEmail,
  ttlMinutes,
}: SaveReportInput): Promise<string> {
  if (!Number.isFinite(ttlMinutes) || ttlMinutes <= 0) {
    throw new Error(`finops-report-store: ttlMinutes must be > 0 (got ${ttlMinutes})`);
  }
  if (!filename) {
    throw new Error("finops-report-store: filename is required");
  }
  if (!userEmail) {
    throw new Error("finops-report-store: userEmail is required");
  }
  if (!Buffer.isBuffer(content) || content.length === 0) {
    throw new Error("finops-report-store: content must be a non-empty Buffer");
  }

  const id = randomUUID();
  const expiresAt = new Date(Date.now() + ttlMinutes * 60_000);

  await pool.query(
    `INSERT INTO finops_reports (id, filename, content, user_email, expires_at)
     VALUES ($1, $2, $3, $4, $5)`,
    [id, filename, content, userEmail, expiresAt],
  );

  return id;
}

/**
 * Retrieves a stored workbook by id. Returns null when the row does not exist or
 * has already expired; expired rows are best-effort deleted on the way out so the
 * table doesn't grow unbounded if no sweeper is running.
 *
 * Errors are NOT swallowed — connection issues bubble up so the caller (the
 * download endpoint) can return a 5xx instead of a misleading 404.
 */
export async function getReport(id: string): Promise<StoredReport | null> {
  if (!id || !UUID_REGEX.test(id)) {
    // Malformed id → behave like "not found" instead of producing a SQL error.
    return null;
  }

  const { rows } = await pool.query<{
    filename: string;
    content: Buffer;
    user_email: string;
    expired: boolean;
  }>(
    `SELECT filename,
            content,
            user_email,
            expires_at <= NOW() AS expired
       FROM finops_reports
      WHERE id = $1`,
    [id],
  );

  if (rows.length === 0) {
    return null;
  }

  const row = rows[0];
  if (row.expired) {
    // Lazy delete: treat as inexistent and best-effort drop the stale row.
    try {
      await pool.query(`DELETE FROM finops_reports WHERE id = $1`, [id]);
    } catch (err) {
      console.warn(
        "[finops-report-store] lazy-delete of expired report failed:",
        (err as Error).message,
      );
    }
    return null;
  }

  return {
    filename: row.filename,
    content: row.content,
    userEmail: row.user_email,
  };
}
