-- Developer name mapping table
-- Maps GitLab usernames to canonical display names
-- Generated from GitLab API audit + manual corrections
-- Applied: 2026-04-20

CREATE TABLE IF NOT EXISTS developer_name_map (
  id SERIAL PRIMARY KEY,
  gitlab_username TEXT NOT NULL UNIQUE,
  gitlab_id INTEGER UNIQUE,
  canonical_name TEXT NOT NULL,
  gitlab_display_name TEXT,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_dev_name_map_username ON developer_name_map(gitlab_username);
CREATE INDEX IF NOT EXISTS idx_dev_name_map_gitlab_id ON developer_name_map(gitlab_id);

-- 86 members from all iskaypet groups (Digital, Retail, Helios, Backoffice, DataBI, SRE-Infra, EducaPet-IT, Friendly Companies)
-- Bots and old accounts excluded
INSERT INTO developer_name_map (gitlab_username, gitlab_id, canonical_name, gitlab_display_name) VALUES
  ('adrian.dominguez2',          28155997,  'Adrián Domínguez',           'adominguez@seidor.es'),
  ('agustin.medina',             14305791,  'Agustín Medina',              'Agustín Medina'),
  ('alberto.salomon',            15614863,  'Alberto Salomon',             'Alberto Salomon'),
  ('alvaro.garcia.m',            14353162,  'Álvaro García',               'Álvaro García'),
  ('andres.arenas',              25298585,  'Andrés Arenas Maciñeira',     'Andrés Arenas Maciñeira'),
  ('andres.hernandez.galindo',   14306915,  'Andrés Hernández',            'andres hernandez'),
  ('apascual.iskaypet',          31077231,  'Andrés Pascual',              'Andres Pascual'),
  ('andres.bravo2',              28592960,  'Andrés Bravo',                'andres.bravo@iskaypet.com'),
  ('antonio.trujillo1',          23424773,  'Antonio Trujillo',            'antonio.trujillo@iskaypet.com'),
  ('ariel.porporatto',           14308107,  'Ariel Porporatto',            'Ariel Porporatto'),
  ('arturo.lorenzo',             14304566,  'Arturo Lorenzo Hernandez',    'Arturo Lorenzo Hernandez'),
  ('borja.torres',               29999115,  'Borja Torres',                'borja.torres@iskaypet.com'),
  ('daniel.romero5',             23139016,  'Daniel Romero',               'daniel.romero@iskaypet.com'),
  ('daniel.rolon',               29447230,  'Daniel Rolón',                'dany.rolon'),
  ('david.merino.p',             12422315,  'David Merino',                'David Merino'),
  ('david.alvarez8',             31208356,  'David Álvarez',               'david.alvarez@ext.iskaypet.com'),
  ('ddiazs1',                    28391492,  'Diego Díaz',                  'ddiazs@seidor.es'),
  ('diegosullon',                28533051,  'Diego Sullon',                'Diego Sullon'),
  ('diego.avila2',               28577246,  'Diego Ávila',                 'diego.avila@iskaypet.com'),
  ('elias.fustero',              20801883,  'Elías Fustero',               'elias.fustero@iskaypet.com'),
  ('ezequiel.ponze',             30815799,  'Ezequiel Ponce',              'ezequiel.ponze@ext.iskaypet.com'),
  ('facundo.arenas.ext.iskaypet',33074453,  'Facundo Arenas',              'Facundo Arenas'),
  ('fernando.ramirez1',          28156000,  'Fernando Ramírez',            'framirez@seidor.es'),
  ('francisca.suarez',           14304655,  'Francisca Suárez Rodríguez',  'Francisca Suarez Rodriguez'),
  ('francisco.blanco2',          20509908,  'Francisco Blanco',            'Francisco Blanco'),
  ('francisco.redondo',          14320684,  'Francisco Redondo',           'Francisco Redondo'),
  ('francisco.valverde',         14286537,  'Francisco Valverde',          'Francisco Valverde'),
  ('francisco.luque',            28690762,  'Francisco Luque',             'francisco.luque@iskaypet.com'),
  ('Giosevid3',                  15096643,  'Giosevid Acosta',             'Giosevid Acosta'),
  ('gonzalo.sanchez.yevenes',    14317228,  'Gonzalo Sánchez',             'Gonzalo Sanchez'),
  ('gonzalo.aguila',             32613178,  'Gonzalo Águila',              'gonzalo.aguila@ext.iskaypet.com'),
  ('hector.garcia4',             28534214,  'Héctor García',               'hector.garcia@iskaypet.com'),
  ('hgmtier1',                   14369853,  'Helio García',                'Helio Garcia'),
  ('ignacio.nayar',              29130695,  'Ignacio Nayar',               'ignacio.nayar@iskaypet.com'),
  ('ivan.belleil',               14332795,  'Ivan Belleil',                'Ivan Belleil'),
  ('ivan.castilla',              20166247,  'Iván Castilla',               'Iván Castilla'),
  ('JaimeMartinSoto',            25382021,  'Jaime Martín Soto',           'Jaime Martín Soto'),
  ('jaime.palomo',               14317936,  'Jaime Palomo',                'Jaime Palomo'),
  ('javier.delpozo1',            31227559,  'Javier del Pozo',             'javier.delpozo@ext.iskaypet.com'),
  ('Jeremias.muriette',          24886087,  'Jeremías Muriette',           'Jeremias Muriette'),
  ('jesus-avila',                14352218,  'Jesús Ávila',                 'Jesús Ávila'),
  ('jesus.furio',                14286944,  'Jesús Furió',                 'Jesús Furió'),
  ('jesus.mari',                 22241158,  'Jesús Marí',                  'jesus.mari@iskaypet.com'),
  ('jordi.salazar1',             35774603,  'Jordi Salazar',               'jordi.salazar@ext.iskaypet.com'),
  ('jorgemarcial',               14351762,  'Jorge Marcial Álvarez',       'Jorge Marcial Alvarez'),
  ('Jorge.Sanchez.Iskaypet',     14331975,  'Jorge Sánchez',               'Jorge Sanchez'),
  ('josealberto.bernal',         14350738,  'José Alberto Bernal',         'Jose Alberto'),
  ('jose.wong',                  28922471,  'José Wong',                   'jose.wong@ext.iskaypet.com'),
  ('juan.marchettini',           24589218,  'Juan Ignacio Marchettini',    'Juan Ignacio Marchettini'),
  ('juanchirc',                  29450469,  'Juan Ignacio Roldán',         'Juan Ignacio Roldan'),
  ('juan.estevez-alonso',        28807335,  'Juan Estévez-Alonso',         'juan.estevez-alonso@viseo.com'),
  ('juan.moral',                 35363564,  'Juan Moral',                  'juan.moral@ext.iskaypet.com'),
  ('laura.ros',                  26020925,  'Laura Ros',                   'laura.ros@iskaypet.com'),
  ('lluis.sanuy1',               30359706,  'Lluís Sanuy',                 'lluis.sanuy@iskaypet.com'),
  ('lucia.morel',                20170071,  'Lu Morel',                    'Lu Morel'),
  ('Lucasmor',                   18624452,  'Lucas Moreira',               'Lucas Moreira'),
  ('lucas.baccillere2',          29446555,  'Lucas Baccillere',            'lucas.baccillere@ext.iskaypet.com'),
  ('luciano.sanchez1',           29599902,  'Luciano Sánchez',             'luciano.sanchez@ext.iskaypet.com'),
  ('mario.fontcuberta',          14318594,  'Mario Fontcuberta',           'Mario Fontcuberta'),
  ('mario.brenaldez',            28962957,  'Mario Bernáldez',             'mario.bernaldez@iskaypet.com'),
  ('marta.prieto',               24818906,  'Marta Prieto',                'Marta Prieto'),
  ('martin.godoy',               29340768,  'Martín Godoy',                'martin.godoy@ext.iskaypet.com'),
  ('martina.padovani',           28923102,  'Martina Padovani',            'Martina Padovani'),
  ('miguel.barrientos2',         29382552,  'Miguel Barrientos',           'miguel.barrientos@ext.iskaypet.com'),
  ('miguelangel.galindo',        31459033,  'Miguel Ángel Galindo',        'miguelangel.galindo@ext.iskaypet.com'),
  ('moises.teixidor',            14332687,  'Moisés Teixidor',             'Moises Teixidor'),
  ('monica.serrano',             28508520,  'Mónica Serrano',              'monica.serrano@iskaypet.com'),
  ('oscar.hernandez7',           25077720,  'Òscar Hernández',             'Òscar Hernández'),
  ('pablo.carabantes',           14305767,  'Pablo Carabantes',            'Pablo Carabantes'),
  ('pablo.diaz8',                24589452,  'Pablo Díaz',                  'Pablo Diaz'),
  ('pablo.villasana',            14306751,  'Pablo Villasana',             'Pablo Villasana'),
  ('pablo.lopezosa',             35116630,  'Pablo Lopezosa',              'pablo.lopezosa@ext.iskaypet.com'),
  ('PrcsPaulo',                  18447297,  'Paulo Cavalcante',            'Paulo Cavalcante'),
  ('pedro.hdez',                 14320538,  'Pedro Hernández',             'Pedro Hdez'),
  ('raul.fluque',                14343945,  'Raúl Fernández Luque',        'Raúl Fernández Luque'),
  ('renzo.daccorso',             32926670,  'Renzo D''Accorso',            'Renzo D''Accorso'),
  ('rodrigo.acevedo1',           29597159,  'Rodrigo Acevedo',             'rodrigo.acevedo@ext.iskaypet.com'),
  ('ruben.landin',               14287595,  'Rubén Landín',                'Ruben Landin'),
  ('Santy.prada',                34900456,  'Santy Prada',                 'santy.prada@iskaypet.com'),
  ('sara.reyes',                 33459831,  'Sara Reyes',                  'sara.reyes@iskaypet.com'),
  ('sebas.hurtado',              14305596,  'Sebastián Hurtado',           'Sebastián Hurtado'),
  ('sergio.lopez.iskaypet',      14561562,  'Sergio López',                'Sergio López'),
  ('sergio.vazquez.rivas',       14316753,  'Sergio Vázquez Rivas',        'Sergio Vázquez Rivas'),
  ('simon.negrin',               14305717,  'Simón Negrín',                'Simón Negrín'),
  ('vanessa.lopez',              14305972,  'Vanessa López Rodríguez',     'Vanessa López Rodríguez'),
  ('yair.oliva',                 28810876,  'Yair Oliva',                  'yair.oliva@ext.iskaypet.com')
ON CONFLICT (gitlab_username) DO UPDATE SET
  canonical_name = EXCLUDED.canonical_name,
  gitlab_display_name = EXCLUDED.gitlab_display_name,
  updated_at = NOW();

-- Total: 86 members
