-- Iskay (FinOps chat) — Excel report store.
--
-- Persists workbooks generated by the `build_report` tool so the download endpoint
-- works across both replicas regardless of which pod served the chat turn. The
-- buffer lives as BYTEA keyed by a UUID generated by the application (lib/finops-
-- report-store.ts). `user_email` is captured at save time so the download endpoint
-- can enforce ownership (domain-normalized) on top of the admin/directores gate.
-- Reports are short-lived (TTL); `expires_at` drives both lazy-delete on read and
-- bulk cleanup, hence the supporting index.

CREATE TABLE IF NOT EXISTS finops_reports (
  id          UUID PRIMARY KEY,
  filename    TEXT NOT NULL,
  content     BYTEA NOT NULL,
  user_email  TEXT NOT NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at  TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_finops_reports_expires_at
  ON finops_reports (expires_at);
