# Auto-generated by Platform team — assign every ArgoCD_<AppSet> Azure AD
# group to all ArgoCD Enterprise Applications so the platform portal can list
# them via /servicePrincipals/{id}/appRoleAssignedTo, and so users get the
# ArgoCD SSO login flow when they accept their assignment in My Apps.
#
# Place this file in iac/services/ of repo
#   iskaypetcom/digital/platform-engineering/azure/azuread
#
# IMPORTANT — Why we look up the app role dynamically:
#   Azure AD only accepts the "default access" role id (all-zeros) when the
#   target Service Principal has *no* appRoles defined. SPs that ship with
#   custom roles (EKS Dev ArgoCD = "AdminTest", ArgoCd Comerzzia Prod =
#   "User"/"msiam_access") reject the all-zeros id with HTTP 400. We discover
#   the catalog at plan time via `data "azuread_service_principal"` and pick
#   the first (alphabetically stable) appRole, falling back to the all-zeros
#   id when the SP has no appRoles defined.

locals {
  # Enterprise App Service Principal Object IDs for ArgoCD instances.
  # Keep in sync with PLATFORM_SP_IDS in
  # src/lib/access-management/platform-groups.ts of platformportal.
  #
  # NOTE: "ArgoCd Comerzzia Prod" (61f786d2-...) is intentionally excluded
  # because that Enterprise App is a SAML SSO app whose `User` role does
  # not accept group-based assignments (Graph returns 400
  # "Permission being assigned was not found on application"). Comerzzia
  # workloads in EKS are reachable via the EKS Prod/Dev/UAT ArgoCD SPs
  # which DO accept group assignments. If anyone ever needs direct SSO
  # to that legacy app, assign them manually as users.
  argocd_sps = {
    "OMS General Argo CD"   = "d4c1136c-b16e-4a53-81fd-3e6f016d71ec"
    "EKS Prod Argo CD"      = "effa022d-719d-49d4-b2e2-72c02966a49d"
    "EKS Dev ArgoCD"        = "fcd7ad35-4976-4543-858e-a7bd080237a9"
    "EKS UAT ArgoCD"        = "a3a9c6dc-2652-49cc-9502-528ca6971497"
    "ArgoCD Dev Comerzzia"  = "80ac0baa-81f2-4c62-94be-e616527e4cbe"
  }

  # Merge the children_group_ids of every PE ArgoCD module into a single
  # map of display_name -> object_id.
  argocd_groups = merge(
    module.pe_argocd_digital.children_group_ids,
    module.pe_argocd_retail.children_group_ids,
    module.pe_argocd_data.children_group_ids,
    module.pe_argocd_martech.children_group_ids,
  )

  # Per-SP appRole id to use. The data source exposes app_role_ids as a map
  # of {displayName -> id}. We pick the first available, sorted alphabetically
  # for determinism, and fall back to the implicit default access id if empty.
  argocd_sp_app_role_ids = {
    for sp_name, _ in local.argocd_sps :
    sp_name => length(keys(data.azuread_service_principal.argocd[sp_name].app_role_ids)) > 0
      ? data.azuread_service_principal.argocd[sp_name].app_role_ids[
          sort(keys(data.azuread_service_principal.argocd[sp_name].app_role_ids))[0]
        ]
      : "00000000-0000-0000-0000-000000000000"
  }

  # Cross product (group x sp) → unique key per assignment, stable across plans.
  argocd_assignments = {
    for pair in setproduct(keys(local.argocd_groups), keys(local.argocd_sps)) :
    "${pair[0]}__${pair[1]}" => {
      group_name  = pair[0]
      sp_name     = pair[1]
      group_id    = local.argocd_groups[pair[0]]
      sp_id       = local.argocd_sps[pair[1]]
      app_role_id = local.argocd_sp_app_role_ids[pair[1]]
    }
  }
}

# Data source per SP to discover its appRole catalog at plan time.
data "azuread_service_principal" "argocd" {
  for_each  = local.argocd_sps
  object_id = each.value
}

resource "azuread_app_role_assignment" "argocd" {
  for_each = local.argocd_assignments

  app_role_id         = each.value.app_role_id
  principal_object_id = each.value.group_id
  resource_object_id  = each.value.sp_id
}
