apiVersion: v1
kind: ServiceAccount
metadata:
  name: platformportal-app
  namespace: platformportal
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::444455556666:role/portal-inventory-irsa"
