/**
 * Integration tests for the deterministic IAM modify path of
 * `POST /api/infra-request-v2/modify`.
 *
 * Feature: iam-role-least-privilege — task 8.2.
 * **Validates: Requirements 6.5, 6.7, 6.8**
 *
 * These drive the REAL route handler (`../route#POST`) end to end for the IAM
 * dispatch branch (`resourceType === "iam_role"` + `operation === "iamSelection"`
 * → `handleIamModifyOperation`). Only two boundaries are faked:
 *
 *   - `@/lib/api-auth#requireUserAuth` is module-mocked (Node's experimental
 *     `mock.module`) to return an authenticated session. The real function opens
 *     with `getServerSession(authOptions)`, which needs a live App-Router request
 *     scope that does not exist inside `node:test`; mocking it lets us exercise
 *     the handler body directly. Everything downstream (catalog, generator,
 *     validator, resource-scope-verifier) is the REAL implementation.
 *   - The singletons `repoCatalog.getByTeam` and `gitlabClient.getRepositoryFileRaw`
 *     are monkey-patched per test (they are mutable methods on exported instances,
 *     so no module mock is needed). `getRepositoryFileRaw` returns a fixture
 *     `roles.tf` generated by the REAL `generateIamRoleHcl`, so `parseRolePresetIds`
 *     recovers genuine catalog preset ids from it (round-trip, Req 6.2).
 *
 * The generated HCL is deterministic (no InfraAgent involved), so assertions on
 * `terraformPreview.content` are stable.
 *
 * RDS data-plane note (Req 6.8): the published Catálogo_IAM deliberately EXCLUDES
 * every preset carrying an RDS data-plane action (`buildPublishedCatalog` drops
 * them via `isRdsDataPlaneAction`). The route's `handleIamModifyOperation` guard
 * (`preset.actions.some(isRdsDataPlaneAction) → 422 rds_data_plane_not_allowed`,
 * before any preview is produced ⇒ no branch/MR — the modify route never touches
 * Git) therefore CANNOT be reached through a real catalog selection. Rather than
 * fake the catalog to synthesise an impossible preset, we assert the guard's
 * correctness honestly at the unit level: the exact predicate the route uses is
 * total and true for every RDS data-plane family, and the catalog invariant that
 * makes the guard unreachable holds. This is the "test the guard is present"
 * path called out by the task.
 *
 * Run (outside the `npm test` glob, module mocking is experimental):
 *   npx tsx --test --experimental-test-module-mocks \
 *     src/app/api/infra-request-v2/modify/__tests__/route.test.ts
 *
 * Conventions: `node:test` + `node:assert/strict`, run with `tsx`, no network.
 */

// `next/server` (pulled in transitively by the route) needs the Web `Request`
// global (Node 18+). Compute availability BEFORE importing anything that touches
// it so the file is safe to parse on older runtimes.
const WEB_API_AVAILABLE =
  typeof (globalThis as { Request?: unknown }).Request !== "undefined";

import { before, describe, it } from "node:test";
import { mock } from "node:test";
import assert from "node:assert/strict";

// Pure modules — safe to import statically (no next/server dependency). These
// are the REAL implementations the route uses; we reuse them to build fixtures
// and to assert the RDS guard invariant.
import { generateIamRoleHcl, sidFromPresetId } from "@/lib/iam-catalog/generator";
import { IAM_CATALOG } from "@/lib/iam-catalog/catalog";
import { isRdsDataPlaneAction } from "@/lib/iam-catalog/action-levels";

const skip = WEB_API_AVAILABLE
  ? false
  : "requires Web API globals (Node 18+)";

/* ------------------------------------------------------------------ */
/*  Fixture: a current shared roles.tf carrying two real presets        */
/* ------------------------------------------------------------------ */

const ROLE_NAME = "my-svc-role";
const NAMESPACE = "oms";

/** Build the "current" roles.tf via the REAL generator (all envs ⇒ no count). */
function buildCurrentRolesTf(): string {
  const gen = generateIamRoleHcl({
    roleName: ROLE_NAME,
    namespace: NAMESPACE,
    selections: [{ presetId: "s3-read-only" }, { presetId: "sqs-consumer" }],
    targetEnvironments: ["dev", "uat", "prod"],
  });
  assert.equal(gen.ok, true, "fixture generation must succeed");
  return (gen as { ok: true; hcl: string }).hcl;
}

const CURRENT_TF = WEB_API_AVAILABLE ? buildCurrentRolesTf() : "";

const SID_S3 = sidFromPresetId("s3-read-only"); // "s3readonly"
const SID_SQS = sidFromPresetId("sqs-consumer"); // "sqsconsumer"
const SID_DDB = sidFromPresetId("dynamodb-read-only"); // "dynamodbreadonly"

/* ------------------------------------------------------------------ */
/*  Lazily-loaded route + singletons (after the api-auth module mock)   */
/* ------------------------------------------------------------------ */

type RouteModule = {
  POST: (request: Request) => Promise<Response>;
};
type RepoCatalogModule = {
  repoCatalog: { getByTeam: (team: string) => Promise<unknown> };
};
type GitlabModule = {
  gitlabClient: {
    getRepositoryFileRaw: (
      projectId: number,
      path: string,
      ref: string,
    ) => Promise<string | null>;
  };
};

let POST: RouteModule["POST"];
let repoCatalog: RepoCatalogModule["repoCatalog"];
let gitlabClient: GitlabModule["gitlabClient"];

before(async () => {
  if (!WEB_API_AVAILABLE) return;

  // Mock the auth boundary so the handler body runs without a live session.
  // `mock.module` keys on the RESOLVED module URL (it does NOT apply the tsconfig
  // `@/` alias), so we point it at the same file the route resolves `@/lib/api-auth`
  // to (src/lib/api-auth.ts) via a relative specifier.
  mock.module("../../../../../lib/api-auth", {
    namedExports: {
      requireUserAuth: async () => ({
        session: { user: { email: "requester@iskaypet.com" }, expires: "2999-01-01" },
        error: null,
      }),
      requireInternalAuth: () => ({ error: null }),
      requireAnyAuth: async () => ({ error: null }),
    },
  });

  ({ POST } = (await import("../route")) as unknown as RouteModule);
  ({ repoCatalog } = (await import(
    "../../../../../lib/repo-catalog"
  )) as unknown as RepoCatalogModule);
  ({ gitlabClient } = (await import(
    "../../../../../lib/gitlab"
  )) as unknown as GitlabModule);
});

/** Point the two boundaries at the given fixture roles.tf. */
function stubBoundaries(currentTf: string | null): void {
  repoCatalog.getByTeam = async (team: string) => ({
    id: 1,
    team,
    gitlabProjectId: 123,
    defaultBranch: "main",
    infraRootPath: "iac",
    description: null,
    active: true,
    createdAt: "2026-01-01",
    updatedAt: "2026-01-01",
  });
  gitlabClient.getRepositoryFileRaw = async () => currentTf;
}

/** Build a POST Request for the IAM `iamSelection` modify branch. */
function iamModifyRequest(selection: {
  addSelections?: unknown;
  removePresetIds?: unknown;
  addManagedArns?: unknown;
}): Request {
  return new Request("http://localhost/api/infra-request-v2/modify", {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify({
      team: "digital",
      resourceType: "iam_role",
      resourceName: ROLE_NAME,
      operation: "iamSelection",
      ...selection,
    }),
  });
}

/* ================================================================== */
/*  (a) Add a covered preset → deterministic HCL with the new Sid       */
/* ================================================================== */

describe("IAM modify — add a covered preset (Req 6.6)", () => {
  it("returns 200 with deterministic HCL containing the added preset Sid", { skip }, async () => {
    stubBoundaries(CURRENT_TF);

    const res = await POST(iamModifyRequest({ addSelections: [{ presetId: "dynamodb-read-only" }] }));
    assert.equal(res.status, 200);

    const body = (await res.json()) as {
      terraformPreview: { content: string; resourceType: string };
      aiReply: string;
    };
    const content = body.terraformPreview.content;

    // The added preset appears...
    assert.ok(content.includes(`"${SID_DDB}"`), "added preset Sid must be present");
    // ...and the pre-existing presets are conserved.
    assert.ok(content.includes(`"${SID_S3}"`), "existing s3 preset Sid must be conserved");
    assert.ok(content.includes(`"${SID_SQS}"`), "existing sqs preset Sid must be conserved");
    // Deterministic (no model): the reply states it was done sin agente IA.
    assert.match(body.aiReply, /sin agente IA/);
    assert.equal(body.terraformPreview.resourceType, "iam_role");
  });

  it("is byte-identical across two equivalent invocations (deterministic)", { skip }, async () => {
    stubBoundaries(CURRENT_TF);
    const first = (await (
      await POST(iamModifyRequest({ addSelections: [{ presetId: "dynamodb-read-only" }] }))
    ).json()) as { terraformPreview: { content: string } };

    stubBoundaries(CURRENT_TF);
    const second = (await (
      await POST(iamModifyRequest({ addSelections: [{ presetId: "dynamodb-read-only" }] }))
    ).json()) as { terraformPreview: { content: string } };

    assert.equal(first.terraformPreview.content, second.terraformPreview.content);
  });
});

/* ================================================================== */
/*  (b) Remove a current preset → exact complement                      */
/* ================================================================== */

describe("IAM modify — remove a current preset (Req 6.7)", () => {
  it("omits exactly the removed preset and keeps the others", { skip }, async () => {
    stubBoundaries(CURRENT_TF);

    const res = await POST(iamModifyRequest({ removePresetIds: ["sqs-consumer"] }));
    assert.equal(res.status, 200);

    const body = (await res.json()) as { terraformPreview: { content: string } };
    const content = body.terraformPreview.content;

    // The removed preset is gone...
    assert.ok(!content.includes(`"${SID_SQS}"`), "removed preset Sid must be absent");
    assert.ok(!content.includes("sqs:ReceiveMessage"), "removed preset actions must be absent");
    // ...and the surviving preset (and its actions) are conserved unchanged.
    assert.ok(content.includes(`"${SID_S3}"`), "surviving preset Sid must remain");
    assert.ok(content.includes("s3:GetObject"), "surviving preset actions must remain");
  });
});

/* ================================================================== */
/*  (c) Admin managed ARN → rejected with reason, valid one conserved   */
/* ================================================================== */

describe("IAM modify — managed ARN partition (Req 6.5)", () => {
  it("rejects the admin managed ARN with a rule and conserves the valid one", { skip }, async () => {
    stubBoundaries(CURRENT_TF);

    const adminArn = "arn:aws:iam::aws:policy/AdministratorAccess";
    const validArn = "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess";

    const res = await POST(
      iamModifyRequest({ addManagedArns: [adminArn, validArn] }),
    );
    assert.equal(res.status, 200);

    const body = (await res.json()) as {
      terraformPreview: { content: string };
      managedArns: {
        accepted: string[];
        rejected: Array<{ arn: string; rule?: string; detail?: string }>;
      };
    };

    // The admin ARN is rejected, with the concrete rule preserved.
    assert.equal(body.managedArns.rejected.length, 1);
    assert.equal(body.managedArns.rejected[0].arn, adminArn);
    assert.equal(body.managedArns.rejected[0].rule, "managed_administrator");

    // The valid ARN is conserved (accepted) — the rest of the selection is intact.
    assert.deepEqual(body.managedArns.accepted, [validArn]);
    // ...and it is attached in the generated HCL, while the admin ARN is not.
    assert.ok(body.terraformPreview.content.includes(validArn));
    assert.ok(!body.terraformPreview.content.includes(adminArn));
  });

  it("rejects a FullAccess managed ARN with the managed_full_access rule", { skip }, async () => {
    stubBoundaries(CURRENT_TF);

    const fullAccessArn = "arn:aws:iam::aws:policy/AmazonS3FullAccess";
    const res = await POST(iamModifyRequest({ addManagedArns: [fullAccessArn] }));
    assert.equal(res.status, 200);

    const body = (await res.json()) as {
      managedArns: { accepted: string[]; rejected: Array<{ arn: string; rule?: string }> };
    };
    assert.equal(body.managedArns.accepted.length, 0);
    assert.equal(body.managedArns.rejected.length, 1);
    assert.equal(body.managedArns.rejected[0].rule, "managed_full_access");
  });
});

/* ================================================================== */
/*  (d) RDS data-plane guard (Req 6.8)                                   */
/* ================================================================== */

describe("IAM modify — RDS data-plane rejection (Req 6.8)", () => {
  // The route guard is `preset.actions.some(isRdsDataPlaneAction)` → 422
  // `rds_data_plane_not_allowed`, produced BEFORE any preview (⇒ no branch/MR).
  // It is unreachable through the real catalog because the catalog excludes all
  // RDS data-plane presets. We therefore validate the guard's building blocks
  // and the catalog invariant that keeps the route safe.

  it("isRdsDataPlaneAction is total and true for every RDS data-plane family", () => {
    // rds-db:*  (IAM DB auth)
    assert.equal(isRdsDataPlaneAction("rds-db:connect"), true);
    // rds-data:* (RDS Data API)
    assert.equal(isRdsDataPlaneAction("rds-data:ExecuteStatement"), true);
    // rds:Connect* (IAM connect to proxy/cluster)
    assert.equal(isRdsDataPlaneAction("rds:Connect"), true);
    // Non data-plane actions are false.
    assert.equal(isRdsDataPlaneAction("s3:GetObject"), false);
    assert.equal(isRdsDataPlaneAction("rds:DescribeDBInstances"), false);
    // Total: never throws for hostile input.
    assert.equal(isRdsDataPlaneAction(undefined as unknown as string), false);
    assert.equal(isRdsDataPlaneAction(123 as unknown as string), false);
  });

  it("no published catalog preset carries an RDS data-plane action (guard is unreachable via catalog)", () => {
    for (const preset of IAM_CATALOG) {
      assert.ok(
        !preset.actions.some((a) => isRdsDataPlaneAction(a)),
        `preset ${preset.id} must not grant RDS data-plane access`,
      );
    }
  });

  it("mirrors the route guard predicate: a synthetic RDS preset would trip the guard", () => {
    // This is the exact boolean the route computes for each finalSelection.
    const syntheticRdsPresetActions = ["rds-db:connect", "s3:GetObject"];
    const wouldReject = syntheticRdsPresetActions.some((a) => isRdsDataPlaneAction(a));
    assert.equal(wouldReject, true);

    // A real catalog preset never trips it.
    const realPreset = IAM_CATALOG.find((p) => p.id === "s3-read-write");
    assert.ok(realPreset);
    assert.equal(
      realPreset!.actions.some((a) => isRdsDataPlaneAction(a)),
      false,
    );
  });
});
